
[package]
name = 'ledger_account'
type = 'contract'
authors = ['']
compiler_version = '>=0.18.0'

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/aztec-nr/aztec' }
safe_math = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/aztec-nr/safe-math' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.9', directory = 'yarn-project/aztec-nr/authwit' }
